### PR TITLE
#19 - Replace JSON.simple by Orbit bundle - org.google.gson

### PR DESCRIPTION
**Pull request by zulus**
Initial replacement.

### CODE REVIEW

**Comment by gossi** [comment]
Looks great :+1: 

I remember, when I looked at a json library it was impossible to retain the order the original composer.json was written. I'm glad this is possible now and you found a way to incorporate it within the java bindings.

**Comment by zulus** [comment]
I'm thinking about reducing additional abstraction layer (com.dubture.getcomposer.core.entites) and use gson transformers rather than raw JsonParser api.

What you think?

**Comment by gossi** [comment]
I hadn't had my head into that library for a longer time and neither do I know what recent versions of gson offer. You are more up-to-date on this for sure. Do whatever looks good.

One thing I know: The `com.dubture.getcomposer.core.entities.Entity` has `PropertyChangeListener` support, which is critical for the composer editor to work. If that still works, go ahead.

**Comment by zulus** [comment]
I'm merging this for now. More work can be done as separate patches.

**Pull request merged**
